#!/bin/sh

#
# 2012.09.19 Brian Elliott Finley <bfinley@us.ibm.com>
#
#   - The core of this I coopted from the command line from Scott
#     Denham.  Thanks, Scott!
#

#
# Use this script to verify that your storage nodes are using the
# desired settings for each block device. -BEF-
#
#   Example usage:
#
#       scp test_nsd_block_device_settings nsd1:/root/
#       ssh nsd1 ./test_nsd_block_device_settings
#

CONTROLLER_REGEX='(1746|1818)'
    #
    #   1746 => ds3512
    #   1818 => dcs3700
    #

DM_DEVICES=$(multipath -ll | egrep $CONTROLLER_REGEX | awk '{print $3}')
SD_DEVICES=$(multipath -ll | grep ' active ' | perl -pi -e 's/.*\d+:\d+:\d+:\d+ (\D+).*/$1/')

for k in $DM_DEVICES $SD_DEVICES
do

	echo -n "$k: "
	# 4096 
	cat /sys/block/$k/queue/max_sectors_kb | perl -pi -e 's/\n/ /'
	
	# 512 
	cat /sys/block/$k/queue/nr_requests | perl -pi -e 's/\n/ /'
	
	# 4096 
	cat /sys/block/$k/queue/read_ahead_kb | perl -pi -e 's/\n/ /'
	
	# noop 
	cat /sys/block/$k/queue/scheduler | perl -pi -e 's/\n/ /'

	echo

done

#
# Example output:
#
#   dm-16: 4096 512 4096 [noop] anticipatory deadline cfq  
#   dm-41: 4096 512 4096 [noop] anticipatory deadline cfq  
#   dm-23: 4096 512 4096 [noop] anticipatory deadline cfq  
#   dm-44: 4096 512 4096 [noop] anticipatory deadline cfq  
#   sdak: 4096 512 4096 [noop] anticipatory deadline cfq  
#   sdg: 4096 512 4096 [noop] anticipatory deadline cfq  
#   sdbp: 4096 512 4096 [noop] anticipatory deadline cfq  
#   sdcn: 4096 512 4096 [noop] anticipatory deadline cfq  
#   sdby: 4096 512 4096 [noop] anticipatory deadline cfq  
#

