#!/bin/sh

#
#   2012.06.28 Brian Elliott Finley <bfinley@us.ibm.com>
#

#
#   This script will hot add LUNs from DS35xx and DCS37xx series
#   devices.  It will also hot remove any devices that no longer exist.
#   It will _NOT_ hot remove any devices that do still exist. -BEF-
#


# 
# Hot delete any devices that don't have disk devices associated with them
#

delete_me=$(lsscsi | egrep '(1818|1746)' | grep -v sd | sed -e 's/.*\[//' -e 's/].*//')
if [ ! -z "$delete_me" ]; then
    echo
    echo "Hot removing undefined LUNs:"
    echo
fi
for i in $delete_me
do
    file="/sys/class/scsi_device/${i}/device/delete"
    echo "  echo 1 > $file"
    echo 1 > $file
done
echo



# 
# Hot add all new devices
#

add_me=$(/bin/ls /sys/class/scsi_host/host*/scan)
if [ ! -z "$add_me" ]; then
    echo
    echo "Discovering and hot-adding new LUNs:"
    echo
fi

for i in $add_me
do
    echo "  echo '- - -' > $i"
    echo '- - -' > $i
done
echo

echo "Total LUN count:"
lsscsi | grep '(1818|1746)' |wc -l
echo

