#!/bin/bash

#
#   2014.05.23 Brian Elliott Finley
#   - created for live demo at Edge2014
#

echo 
echo "This is just example code right now. -Brian"
echo
sleep 1
cat $0 | less -i

#
# Options
#
#   --servers SERVER1[,SERVER2,...]
#
#   ASSUMPTION:  It is assumed that each server is dual-connected to
#   each storage controller -- one to RAID controller A and one to RAID
#   controller B.
#
#   WARNING: If the above ASSUMPTION is not the case, then you should
#   either change the connectivity (so that it matches the ASSUMPTION)
#   or use some other method to create your disk StanzaFile to achive
#   optimal performance.
#


server1=surnsd1
server2=surnsd2

count=1
CONTROLLER_REGEX='[ab]_lun[0-9]+'
for lun in $(ls -1 /dev/mapper/ | egrep $CONTROLLER_REGEX | awk -F'lun' '{print $2" "$1"lun"$2}' | sort -n | awk '{print $NF}')
do 
	NsdName=$(basename $lun)
	if [ $count -le 2 ]; then
		servers=$server1,$server2
	else
		servers=$server2,$server1
	fi
	echo %nsd: device=$lun  nsd=$NsdName  servers=$servers

	if [ $count -eq 4 ]; then
		count=1
	else
		count=$(( $count + 1 ))
	fi
done



