#!/bin/bash

#
# 2013.09.27 Brian Elliott Finley <bfinley@us.ibm.com>
# 2013.11.07 Brian Elliott Finley <bfinley@us.ibm.com>
#

cat <<"EOF"

gpfs_goodies v__VERSION__

Please try one of the following commands.  It's OK -- they're all safe,
and won't do anything but show help information if run with either no
arguments, or with --help or -h as an argument.

    multipath.conf-creator
    test_block_device_settings
    brians_own_hot-add_script

    Be sure to take a look at the HOWTO and other docs in:

        /usr/share/doc/gpfs_goodies-__VERSION__

EOF

