#!/bin/bash

#
# StanzaFile-creator
#

#   2012.10.16 Brian Elliott Finley <bfinley@us.ibm.com>
#   - added invocation options and help output

server1=$1
server2=$2

if [ -z $server2 ]; then
    echo "
Usage: $0 SERVER1 SERVER2

    This script should be considered an example of how you can create a
    StanzaFile that will appropriately balance your disk devices across
    your NSD servers for balanced performance.  
    
    WARNING:  This script should work as-is for a GPFS building block
    that:
    a) includes two NSD servers
    b) that are both multipathed to the same storage subsystem
    c) that have been prepared for use with the GPFS Goodies
       multipath.conf-creator tool.

    Please review your StanzaFile for appropriateness before using, and
    you may need to modify this script or use an alternate method for
    use with different building block configurations.

    Have fun!  -Brian Finley

"
    exit 1
fi


CONTROLLER_REGEX='[ab]_lun[0-9]+'

count=1
for lun in $(ssh $server1 ls -1 /dev/mapper/* | egrep $CONTROLLER_REGEX | awk -F'lun' '{print $2" "$1"lun"$2}' | sort -n | awk '{print $NF}')
do 
	NsdName=$(basename $lun)
	if [ $count -le 2 ]; then
		servers=$server1,$server2
	else
		servers=$server2,$server1
	fi
	echo %nsd: device=$lun  nsd=$NsdName  servers=$servers

	if [ $count -eq 4 ]; then
		count=1
	else
		count=$(( $count + 1 ))
	fi
done



